In [127]:
import math
import numpy as np
import matplotlib.pyplot as plt
import imp

import figure_functions
import pattern_functions
#from parameter_functions import ParameterClass
import parameter_functions
imp.reload(parameter_functions)
imp.reload(pattern_functions)
imp.reload(figure_functions)

<module 'figure_functions' from '/Users/amandasiewertdelle/Documents/KTH/KEX/KEXcode/figure_functions.py'>

In [128]:
a = 1; b = 2; c = 3; d = 4; D_x = 1; D_y = 2
print("a=", a,", b=", b,", c=", c,", d=", d,", D_x=", D_x,", D_y=", D_y,)
morphogens = 2

#rows and columns that we are looking at. The whole cell grid is rows+2 and columns+2 because we are ignoring the edges.
cellRows = 3 
cellColumns = 3
print("Morphogens:",morphogens)
print()
print("Inner grid of cells is", cellRows,"x", cellColumns)

a= 1 , b= 2 , c= 3 , d= 4 , D_x= 1 , D_y= 2
Morphogens: 2

Inner grid of cells is 3 x 3


In [129]:
#How many rows and columns matrix A has:
ARows = cellRows*cellColumns*morphogens
AColumns = cellRows*cellColumns*morphogens
print("size of A: ", ARows,"x",AColumns)
A = np.zeros([ARows,AColumns]) #Creating an empty A-matrix

for m1 in range(0,morphogens): #Number of morphogens     
        for cr1 in range(0,cellRows):
            for cc1 in range(0,cellColumns):
                for m2 in range(0,morphogens):
                    for cr2 in range(0,cellRows):
                        for cc2 in range(0,cellColumns):
                            rA = m1*cellRows*cellColumns + cr1*cellColumns + cc1 
                            cA = m2*cellRows*cellColumns + cr2*cellColumns + cc2 # realized now that I could have written cA +=1 instead
                            if (m1==m2):
                                if (cc1==cc2 and cr1==cr2):
                                    A[rA,cA] = (-4*D_x + a)*((m1+1)%2) + (-4*D_y + b)*(m1)
                                elif ((cc1-1==cc2 and cr1==cr2) or 
                                      (cc1+1==cc2 and cr1==cr2) or 
                                      (cr1-1==cr2 and cc1==cc2) or 
                                      (cr1+1==cr2 and cc1==cc2)):
                                    A[rA,cA] = D_x*((m1+1)%2) + D_y*(m1)
                            else:
                                if (cc1==cc2 and cr1==cr2):
                                    A[rA,cA] = (b)*((m1+1)%2) + (d)*(m1)
print(A)
print()

morphogenInput = 1   #How many morphogens we use as input. (Right now we use the concentration of all neighbouring cells as input.)
print("We use", morphogenInput, "morphogen(s) as input")

size of A:  18 x 18
[[-3.  1.  0.  1.  0.  0.  0.  0.  0.  2.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1. -3.  1.  0.  1.  0.  0.  0.  0.  0.  2.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1. -3.  0.  0.  1.  0.  0.  0.  0.  0.  2.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0. -3.  1.  0.  1.  0.  0.  0.  0.  0.  2.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  1. -3.  1.  0.  1.  0.  0.  0.  0.  0.  2.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  1. -3.  0.  0.  1.  0.  0.  0.  0.  0.  2.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0. -3.  1.  0.  0.  0.  0.  0.  0.  0.  2.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  1. -3.  1.  0.  0.  0.  0.  0.  0.  0.  2.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  1. -3.  0.  0.  0.  0.  0.  0.  0.  0.  2.]
 [ 4.  0.  0.  0.  0.  0.  0.  0.  0. -6.  2.  0.  2.  0.  0.  0.  0.  0.]
 [ 0.  4.  0.  0.  0.  0.  0.  0.  0.  2. -6.  2.  0.  2.  0.  0.  0.  0.]
 [ 0.  0.  4.  0.  0.  0.  0.  0.  0.  0.  2. -6.  0.  0.  2.  0.  0.  0.]
 [ 0.  0.  0.  4.  0.  0.  0.  0.  0.  2.  0.  0. -6.  2.  0.  2.  0.  0.]
 [ 0.

In [130]:
morphogenInput = 1   #How many morphogens we use as input. (Right now we use the concentration of all neighbouring cells as input.)
print("We use", morphogenInput, "morphogen(s) as input")

#How may rows and columns matrix B has:
BRows = ARows
BColumns = (2*cellRows + 2*cellColumns)*morphogenInput
print("size of B: ", BRows,"x",BColumns)
B = np.zeros([BRows, BColumns]) #Creating an empty B matrix

rB = 0 #row index in the B matrix
for m1 in range(0,morphogenInput): #Number of morphogens we use as input
        for cr1 in range(0,cellRows):
            for cc1 in range(0,cellColumns):
                cB = 0 #columns index in the B matrix
                for m2 in range(0,morphogenInput):
                    for cr2 in range(-1,cellRows+1):
                        for cc2 in range(-1,cellColumns+1): 
                            if ((cr2==-1 and not (cc2==-1 or cc2==cellColumns)) or 
                                (cr2==cellRows and not (cc2==-1 or cc2==cellColumns)) or 
                                (cc2==-1 and not (cr2==-1 or cr2==cellRows)) or 
                                (cc2==cellColumns and not (cr2==-1 or cr2==cellRows))):
                                if ((cc1-1==cc2 and cr1==cr2) or 
                                    (cc1+1==cc2 and cr1==cr2) or 
                                    (cr1-1==cr2 and cc1==cc2) or 
                                    (cr1+1==cr2 and cc1==cc2)):
                                    B[rB,cB] = D_x*((m1+1)%2) + D_y*(m1)
                                cB +=1 #Move one column in the B matrix
                rB +=1 #Move one row in the B matrix
print(B)

We use 1 morphogen(s) as input
size of B:  18 x 12
[[1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [131]:
gRows = BRows
gColumns = BRows*BColumns
gamma = np.zeros([gRows, gColumns])
for c in range(0,3):
#for c in range(0,gRows):
    gamma[:,c*BColumns:(c+1)*BColumns] = np.matmul(np.linalg.matrix_power(A, c),B)
#print(gamma)
rankGamma = np.linalg.matrix_rank(gamma) #, tol=10**(-16))
print("rank of gamma:", rankGamma)
print("size of gamma: ",gRows,"x",gColumns)


rank of gamma: 18
size of gamma:  18 x 216


In [132]:
# Amandas funktion för gamma
def gamma_func(B, A):
    # from theory we have that the A matrix is n x n, and we go from 0 to n-1 when computing the reachability matrix tau ( in our case gamma)
    n = A.shape[0]
    Bnm = B.shape[:]
    # Creating the reachability matrix gamma w zeros
    gamma_shape = (Bnm[0],(Bnm[0]*Bnm[1]))
    gamma = np.zeros(gamma_shape)
    #print(gamma_shape)
    for c in range(0, n):
        gamma[:,c*B.shape[1]:(c+1)*B.shape[1]] = np.matmul(np.linalg.matrix_power(A, c), B)
    gamma_rank = np.linalg.matrix_rank(gamma, tol=10**(-16))
    print(gamma_rank)
    return gamma_rank, gamma_shape

# tol=10**(-16)

In [133]:
def gamma_func2(B, A):    
    gRows = BRows
    gColumns = BRows*BColumns
    gamma = np.zeros([gRows, gColumns])
    rankB = np.linalg.matrix_rank(B)
    #print("räknar rang när (c+1) >= ", gRows/rankB)
    #for c in range(0,2):
    for c in range(0,BRows):
        gamma[:,c*BColumns:(c+1)*BColumns] = np.matmul(np.linalg.matrix_power(A, c),B)
        rankGamma = np.linalg.matrix_rank(gamma)
        if (rankGamma == gRows):
            print("FULL RANK at c =",c)
            break
    gamma_shape =[gRows, gColumns]
    return rankGamma, gamma_shape

In [134]:
# Finding the rank of gamma for different combinations of controlls

# m is the number off cells on the border of the grid
m = 4 #change to 12 (for a 3 x 3 cell grid) B.shape[1]
roof = 2**(B.shape[1]) - 1

controllerData = np.zeros([roof+1, 3])


for i in range(0, roof + 1):
    Bbeta = B.copy()
    controllerData[i, 0] = i
    binNum = bin(i)
    array = [x for x in str(binNum)]
    array.reverse()
    numberOfInputs = 0
    for j in range(0,len(array)-1):
        if array[j] == '0':
            Bbeta[:, j] = 0
        elif array[j] == '1':
            numberOfInputs += 1
        elif array[j] == 'b':
            Bbeta[:, j::] = 0
            break
    controllerData[i, 1] = numberOfInputs
    gamma_rank, gamma_shape = gamma_func2(Bbeta, A)
    controllerData[i, 2] = gamma_rank
    #print(type(gamma_rank), 'and', type(gamma_shape))
    #print('for i = ', i, ':\n the rank of gamma is ', gamma_rank, '\n the size of gamma is', gamma_shape)


FULL RANK at c = 5
FULL RANK at c = 5
FULL RANK at c = 5
FULL RANK at c = 5
FULL RANK at c = 5
FULL RANK at c =

 5
FULL RANK at c = 5
FULL RANK at c = 5
FULL RANK at c = 5
FULL RANK at c = 5
FULL RANK at c = 4
FULL RANK at c = 5
FULL RANK at c = 5
FULL RANK at c = 4
FULL RANK at c = 4
FULL RANK at c = 5
FULL RANK at c = 4
FULL RANK at c = 5
FULL RANK at c = 4
FULL RANK at c = 5
FULL RANK at c = 5
FULL RANK at c = 4
FULL RANK at c = 4
FULL RANK at c = 5
FULL RANK at c = 5
FULL RANK at c = 4
FULL RANK at c = 4
FULL RANK at c = 5
FULL RANK at c = 4
FULL RANK at c = 5
FULL RANK at c = 5
FULL RANK at c = 4
FULL RANK at c = 4
FULL RANK at c = 5
FULL RANK at c = 4
FULL RANK at c = 5
FULL RANK at c = 4
FULL RANK at c = 5
FULL RANK at c = 5
FULL RANK at c = 4
FULL RANK at c = 4
FULL RANK at c = 5
FULL RANK at c = 5
FULL RANK at c = 4
FULL RANK at c = 4
FULL RANK at c = 5
FULL RANK at c = 3
FULL RANK at c = 5
FULL RANK at c = 5
FULL RANK at c = 3
FULL RANK at c = 3
FULL RANK at c = 5
FULL RANK at c = 3
FULL RANK at c = 5
FULL RANK at c = 3
FULL RANK at c = 5
FULL RANK at c = 5
FULL RANK at c = 3
FULL RANK

In [135]:
for i in range(len(controllerData[:, 2])):
    print('value of i: ', controllerData[i, 0])
    print('number of controllers: ', controllerData[i, 1])
    print('rank of gamma: ', controllerData[i, 2])
    print('\n')

value of i:  0.0
number of controllers:  0.0
rank of gamma:  0.0


value of i:  1.0
number of controllers:  1.0
rank of gamma:  6.0


value of i:  2.0
number of controllers:  1.0
rank of gamma:  6.0


value of i:  3.0
number of controllers:  2.0
rank of gamma:  10.0


value of i:  4.0
number of controllers:  1.0
rank of gamma:  6.0


value of i:  5.0
number of controllers:  2.0
rank of gamma:  10.0


value of i:  6.0
number of controllers:  2.0
rank of gamma:  10.0


value of i:  7.0
number of controllers:  3.0
rank of gamma:  18.0


value of i:  8.0
number of controllers:  1.0
rank of gamma:  6.0


value of i:  9.0
number of controllers:  2.0
rank of gamma:  6.0


value of i:  10.0
number of controllers:  2.0
rank of gamma:  10.0


value of i:  11.0
number of controllers:  3.0
rank of gamma:  10.0


value of i:  12.0
number of controllers:  2.0
rank of gamma:  10.0


value of i:  13.0
number of controllers:  3.0
rank of gamma:  10.0


value of i:  14.0
number of controllers:  3.0
rank

In [136]:

i = 10
binNum = bin(9)
array = [x for x in str(binNum)]
len(array)
for n in range(len(array) - 1, -1, -1):
   print(array[n])

Bbeta = B.copy()
array = [x for x in str(binNum)]
array.reverse()
for j in range(0,len(array)-1):
   if array[j] == '0':
      print('inside')
      Bbeta[:, j] = 0
   elif array[j] == 'b':
      print('j = ', j, 'broken')
      break

print(Bbeta)

1
0
0
1
b
0
inside
inside
j =  4 broken
[[1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [137]:
i = 1
Bbeta = B.copy()
binNum = bin(i)
array = [x for x in str(binNum)]
array.reverse()
for j in range(0,len(array)-1):
    if array[j] == '0':
        Bbeta[:, j] = 0
    elif array[j] == 'b':
        Bbeta[:, j::] = 0
        break
gamma_rank, gamma_shape = gamma_func(Bbeta, A)
#print(type(gamma_rank), 'and', type(gamma_shape))
print('for i = ', i, ':\n the rank of gamma is ', gamma_rank, '\n the size of gamma is', gamma_shape)

print('Bbeta = \n', Bbeta)

18
for i =  1 :
 the rank of gamma is  18 
 the size of gamma is (18, 216)
Bbeta = 
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [138]:
X = np.zeros([18,12])
gamma_rank = np.linalg.matrix_rank(, tol=10**(-16))
print(gamma_rank)


SyntaxError: invalid syntax (498829684.py, line 2)